# Generated by Django 4.2.29 on 2026-09-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_book_related_gt_books_se_match_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='format',
            name='modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
